name: Build release

on:
  workflow_dispatch:
  push:
    # branches: ["main"]
    tags:
      - "v*"

jobs:
  fetch_latest_version:
    name: Fetch Latest Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.fetch_and_configure.outputs.version }}
      release_name: ${{ steps.fetch_and_configure.outputs.release_name }}
      build_time: ${{ steps.fetch_and_configure.outputs.build_time }}
      can_release: ${{ steps.fetch_and_configure.outputs.can_release }}
    steps:
      - name: Configure Variables
        id: fetch_and_configure
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            version="${{ github.ref_name }}"
            release_name="${{ github.ref_name }} Release"
          else
            response=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -L "https://api.github.com/repos/${{ github.repository }}/releases/latest")
            version=$(echo "$response" | jq -r .tag_name)
            release_name=$(echo "$response" | jq -r .name)
          fi

          build_time=$(TZ=Asia/Shanghai date '+%Y%m%d%H%M')

          echo "version=$version" >> $GITHUB_OUTPUT
          echo "release_name=$release_name" >> $GITHUB_OUTPUT
          echo "build_time=$build_time" >> $GITHUB_OUTPUT

          if [[ -n "$version" && "$version" != "null" && -n "$release_name" && "$release_name" != "null" ]]; then
            echo "can_release=true" >> $GITHUB_OUTPUT
          else
            echo "can_release=false" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: archlinux
            version: current
          - os: alpine
            version: edge
          - os: centos
            version: 9-Stream
          - os: debian
            version: bookworm
          - os: fedora
            version: 42
          - os: kali
            version: current
          - os: ubuntu
            version: oracular

    env:
      OS: ${{ matrix.os }}
      VERSION: ${{ matrix.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Package for OS ${{ matrix.os }} Version ${{ matrix.version }}
        run: |
          cd Module
          sed -i "s|^LXC_OS=.*|LXC_OS=$OS|g" config.conf
          sed -i "s|^LXC_OS_VERSION=.*|LXC_OS_VERSION=$VERSION|g" config.conf
          sed -i "s|^CONTAINER_DIR=.*|CONTAINER_DIR=/data/$OS|g" config.conf

          zip -r "../asl-$OS-$VERSION.zip" .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asl-${{ matrix.os }}-${{ matrix.version }}
          path: ./asl-${{ matrix.os }}-${{ matrix.version }}.zip
          retention-days: 7

  release:
    name: Release
    needs: [fetch_latest_version, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: |
      (github.event_name == 'workflow_dispatch' && needs.fetch_latest_version.outputs.can_release) ||
      startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Download All Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Move Artifacts
        run: |
          find ./artifacts -type f -name "*.zip" -exec mv {} ./ \;

      - name: Update Artifacts
        run: |
          cd Module
          rm -f config.conf
          sed -i 's/^ASL=""/ASL="1"/' customize.sh
          zip -r "../asl.zip" .

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.fetch_latest_version.outputs.version }}
          name: ${{ needs.fetch_latest_version.outputs.release_name }}
          body: |
            You can only install one of these modules.
          prerelease: false
          files: |
            ./*.zip
